### ISSUE TITLE
Unable to play ,Socket timed out

### ISSUE THREAD

**Issue by msycn** [jarnedemeulemeester/findroid#182]
**Describe the bug**
Unable to play ,Socket timed out
But after 30s the movie will steam

**To Reproduce**
1. Go to 'Movie'
2. Click on 'play'
3. See error

**Expected behavior**

**Screenshots**
![Screenshot_2022-10-22-02-24-18-162_com netflix mediaclient](https://user-images.githubusercontent.com/85003651/197323908-9ce5d21a-ef6f-4921-a7e3-030e6e85fa0a.jpg)

**Device info (please complete the following information):**
 - Device: [Xiaomi 12S Ultra]
 - Android version: [12]
 - App version: [v0.6.1]

**Additional context**
Socket timed out
 sa.g: Socket timed out
	at ra.e.l(SourceFile:4)
	at ra.e$d.j(Unknown Source:17)
	at v8.a.k(Unknown Source:8)
	at e8.j.d(SourceFile:5)
	at e8.j$a.k(SourceFile:3)
	at v8.a.k(Unknown Source:31)
	at e8.j.d(SourceFile:5)
	at e8.j$a.k(SourceFile:3)
	at v8.a.k(Unknown Source:31)
	at e8.j.d(SourceFile:5)
	at e8.j$a.k(SourceFile:3)
	at v8.a.k(Unknown Source:31)
	at e8.j.d(SourceFile:5)
	at e8.j$a.k(SourceFile:3)
	at v8.a.k(Unknown Source:31)
	at k9.q0.run(Unknown Source:86)
	at p9.e.run(Unknown Source:12)
	at q9.l.run(Unknown Source:2)
	at q9.a$a.run(SourceFile:9)
Caused by: x7.b: Socket timeout has expired [url=ip:8096/Items/f5c06709-ad16-d695-36b1-3250770a31f7/PlaybackInfo, socket_timeout=10000] ms
	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(SourceFile:2)
	at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(Unknown Source:22)
	at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(Unknown Source:0)
	at p7.a.a(Unknown Source:18)
	at fa.e$a.run(SourceFile:13)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:920)
Caused by: java.net.SocketTimeoutException: timeout
	at oa.y.k(Unknown Source:4)
	at oa.d.s(SourceFile:3)
	at oa.t.b(SourceFile:2)
	at oa.t.Y(Unknown Source:34)
	at ha.b.g(SourceFile:1)
	at fa.c.d(Unknown Source:2)
	at ga.b.a(SourceFile:29)
	at ga.g.b(SourceFile:7)
	at fa.a.a(SourceFile:16)
	at ga.g.b(SourceFile:7)
	at da.a.a(SourceFile:29)
	at ga.g.b(SourceFile:7)
	at ga.a.a(SourceFile:21)
	at ga.g.b(SourceFile:7)
	at ga.i.a(SourceFile:26)
	at ga.g.b(SourceFile:7)
	at fa.e.f(SourceFile:10)
	at fa.e$a.run(SourceFile:8)
	... 3 more
Caused by: java.net.SocketException: Socket closed
	at java.net.SocketInputStream.read(SocketInputStream.java:209)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at oa.o.s(Unknown Source:45)
	at oa.d.s(Unknown Source:12)
	... 19 more

**Comment by AnonymousWebHacker** [comment]
If you are the owner of the server, you should give details of the video that was tried to play.

Try the first outputs of `ffplay video.mkv`

It would be nice to know the format, etc.

**Comment by msycn** [comment]
> 
https://jellyfin.org/docs/general/networking/nginx/#nginx-from-a-subdomain-jellyfinexampleorg
   add_header X-Frame-Options "SAMEORIGIN";
    add_header X-XSS-Protection "1; mode=block";
    add_header X-Content-Type-Options "nosniff";

Fixed, sorry this is my error. 
You made the best Jellyfin app ever !👍

**Comment by AnonymousWebHacker** [comment]
@msycn Did it work for you with other jellyfin clients and not with findroid?

Or you had not tried with other clients?

I thought you had tried with other clients, and it was a findroid bug, I never thought it was nginx configuration issues

**Comment by msycn** [comment]
> 

Yes, that is server issues , I tired to web client and pc client as same
