### ISSUE TITLE
Playing trailer of movie crashes

### ISSUE THREAD

**Issue by JVT038** [jarnedemeulemeester/findroid#290]
**Describe the bug**
When playing the trailer of a movie item, the app abruptly crashes.

**To Reproduce**
1. Go to a movie
2. Click on the trailer icon
3. See crash

**Expected behavior**
I expected the trailer to be played

**Device info (please complete the following information):**
 - Device: Fairphone 4
 - Android version: Android 12
 - App version: v0.10.1
 - Jellyfin version: v10.8.9

**Logcat**
````
02-14 11:36:36.021 19508 19508 D AndroidRuntime: Shutting down VM
--------- beginning of crash
02-14 11:36:36.022 19508 19508 E AndroidRuntime: FATAL EXCEPTION: main
02-14 11:36:36.022 19508 19508 E AndroidRuntime: Process: dev.jdtech.jellyfin, PID: 19508
02-14 11:36:36.022 19508 19508 E AndroidRuntime: android.content.ActivityNotFoundException: No Activity found to handle Intent { act=android.intent.action.VIEW dat=plugin://plugin.video.youtube/play/?video_id=SA0an0EWchY }
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.app.Instrumentation.checkStartActivityResult(Instrumentation.java:2121)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.app.Instrumentation.execStartActivity(Instrumentation.java:1766)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5410)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.app.Activity.startActivityForResult(Activity.java:5368)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at androidx.activity.ComponentActivity.startActivityForResult(Unknown Source:0)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.app.Activity.startActivity(Activity.java:5754)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at z.a$a.b(Unknown Source:0)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at androidx.fragment.app.o.Z(Unknown Source:9)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at s7.h1.onClick(Unknown Source:414)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.view.View.performClick(View.java:7455)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.view.View.performClickInternal(View.java:7432)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.view.View.access$3700(View.java:835)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:28810)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:938)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:99)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.os.Looper.loopOnce(Looper.java:201)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:288)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:7870)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
02-14 11:36:36.022 19508 19508 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
02-14 11:36:36.041 19508 19508 I Process : Sending signal. PID: 19508 SIG: 9
```

When playing the trailer of a TV show, it doesn't crash. So it only happens with movie trailers.

**Comment by jarnedemeulemeester** [comment]
It seems like Jellyfin is not converting the kodi plugin uri to a normal Youtube url.
https://github.com/jellyfin/jellyfin/blob/6e14f26ec85b8fad3c9412d395f0856a27421852/MediaBrowser.XbmcMetadata/Parsers/BaseNfoParser.cs#L611
It's only looking for the old deprecated uri, not the current one your file is using.

I will fix the crash but I wont be adding the conversion to a normal Youtube url. That's something that has to be fixed in the Jellyfin server.
