### ISSUE TITLE
[BUG] HTTP 404 on Streaming Playback

### ISSUE THREAD

**Issue by sim2kid** [jarnedemeulemeester/findroid#331]
**Describe the bug**
When playing directly from the server, when I press play, I get "Error preparing player items." with the following error log:
```
Invalid HTTP status in response: 404
 ua.c: Invalid HTTP status in response: 404
    at ta.e.l(Unknown Source:516)
    at ta.e$d.q(Unknown Source:17)
    at b9.a.i(Unknown Source:8)
    at m8.k.d(Unknown Source:99)
    at m8.k.c(Unknown Source:15)
    at m8.k$a.i(Unknown Source:22)
    at b9.a.i(Unknown Source:31)
    at m8.k.d(Unknown Source:99)
    at m8.k.c(Unknown Source:15)
    at m8.k$a.i(Unknown Source:22)
    at b9.a.i(Unknown Source:31)
    at m8.k.d(Unknown Source:99)
    at m8.k.c(Unknown Source:15)
    at m8.k$a.i(Unknown Source:22)
    at b9.a.i(Unknown Source:31)
    at m8.k.d(Unknown Source:99)
    at m8.k.c(Unknown Source:15)
    at m8.k$a.i(Unknown Source:22)
    at b9.a.i(Unknown Source:31)
    at kotlinx.coroutines.p0.run(Unknown Source:100)
    at kotlinx.coroutines.internal.g.run(Unknown Source:12)
    at kotlinx.coroutines.scheduling.l.run(Unknown Source:2)
    at kotlinx.coroutines.scheduling.a$a.run(Unknown Source:78)
```

**To Reproduce**
1. Log into your server
2. Select any piece of media
3. Press the play button
4. An error should pop up below

**Expected behavior**
What should happen is that the player opens and the video starts streaming.

**Screenshots**
![image](https://user-images.githubusercontent.com/13566418/230731446-6101615b-3d93-46c4-9d7b-e2f5f840ff0a.png)

**Device info (please complete the following information):**
 - Device: Galaxy S20 Ultra 5G
 - Android version: 13
 - App version: v0.10.1 (17)
 - Jellyfin version: v10.8.9

**Additional context**
Here's the specific file information for the video I tried (Collected with ffprobe):
- Video Codex: `h264 (High) (avc1 / 0x31637661), yuv420p, 1280x720 [SAR 1:1 DAR 16:9], 930 kb/s, 25 fps, 25 tbr, 90k tbn, 50 tbc (default)`
- Audio Codex: `aac (LC) (mp4a / 0x6134706D), 44100 Hz, stereo, fltp, 128 kb/s (default)`
- File Extension: `.mp4`

**Comment by sim2kid** [comment]
It seems this issue stemmed from an issue with the Jellyfin Server itself. As such, this can be considered resolved.
