### ISSUE TITLE
Findroid app can't show media libraries of type "Mixed Movies and Shows"

### ISSUE THREAD

**Issue by maulik-sharma** [jarnedemeulemeester/findroid#352]
**Describe the bug**
Findroid app can't show media libraries of type **Mixed Movies and Shows**

**To Reproduce**
While creating a library in jellyfin set a library's conent type to **Mixed Movies and Shows** will caues it to not display that library in the Findroid app.

**Expected behavior**
Library of content type Mixed Movies and Shows should also be displayed among other libraries in findroid app

**Device info (please complete the following information):**
 - Device: Xiaomi 11i
 - Android version: 13
 - App version: 0.11.0
 - Jellyfin version: 10.8.10

**Additional context**
I have a jellyfin library of content type Mixed Movies and Shows which I use for anime. All the other libraries are properly displayed in FIndroid app but the anime library is not available

**Comment by decisoft** [comment]
For the record, this is the traceback:

`java.lang.NullPointerException
 java.lang.Exception: java.lang.NullPointerException
	at c8.u1.invoke(Unknown Source:144)
	at k3.b1.b(Unknown Source:109)
	at k3.f.a(Unknown Source:31)
	at k3.i3.m(Unknown Source:689)
	at k3.i3.f(Unknown Source:12)
	at ja.q.e0(Unknown Source:4)
	at com.bumptech.glide.f.E0(Unknown Source:71)
	at k3.y.a(Unknown Source:2290)
	at pa.t.e(Unknown Source:4)
	at pa.s.o(Unknown Source:133)
	at pa.s.a(Unknown Source:0)
	at k3.k.a(Unknown Source:77)
	at kotlinx.coroutines.flow.u.a(Unknown Source:102)
	at kotlinx.coroutines.flow.w0.a(Unknown Source:2)
	at kotlinx.coroutines.flow.k0.l(Unknown Source:187)
	at kotlinx.coroutines.flow.j0.m(Unknown Source:12)
	at x9.a.h(Unknown Source:8)
	at kotlinx.coroutines.m0.run(Unknown Source:102)
	at kotlinx.coroutines.x0.o0(Unknown Source:38)
	at kotlinx.coroutines.l.o(Unknown Source:107)
	at oa.b.c(Unknown Source:6)
	at oa.m.p(Unknown Source:89)
	at oa.j.j(Unknown Source:0)
	at k3.t2.i(Unknown Source:31)
	at k3.t2.f(Unknown Source:505)
	at k3.c2.m(Unknown Source:11)
	at x9.a.h(Unknown Source:8)
	at kotlinx.coroutines.m0.run(Unknown Source:102)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7884)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936)
Caused by: java.lang.NullPointerException
	at hb.d.A(Unknown Source:417)
	at n4.f.P0(Unknown Source:59)
	at f8.j.m(Unknown Source:171)
	at x9.a.h(Unknown Source:8)
	at kotlinx.coroutines.m0.run(Unknown Source:102)
	at kotlinx.coroutines.internal.f.run(Unknown Source:12)
	at kotlinx.coroutines.scheduling.l.run(Unknown Source:2)
	at kotlinx.coroutines.scheduling.a.run(Unknown Source:78)
`

When accessing to the library that has mixed content fron the Home page, through "View all" in recently added to that library

**Comment by abarsa** [comment]
I have same Issue

**Comment by decisoft** [comment]
> For the record, this is the traceback:
> 
> `java.lang.NullPointerException java.lang.Exception: java.lang.NullPointerException at c8.u1.invoke(Unknown Source:144) at k3.b1.b(Unknown Source:109) at k3.f.a(Unknown Source:31) at k3.i3.m(Unknown Source:689) at k3.i3.f(Unknown Source:12) at ja.q.e0(Unknown Source:4) at com.bumptech.glide.f.E0(Unknown Source:71) at k3.y.a(Unknown Source:2290) at pa.t.e(Unknown Source:4) at pa.s.o(Unknown Source:133) at pa.s.a(Unknown Source:0) at k3.k.a(Unknown Source:77) at kotlinx.coroutines.flow.u.a(Unknown Source:102) at kotlinx.coroutines.flow.w0.a(Unknown Source:2) at kotlinx.coroutines.flow.k0.l(Unknown Source:187) at kotlinx.coroutines.flow.j0.m(Unknown Source:12) at x9.a.h(Unknown Source:8) at kotlinx.coroutines.m0.run(Unknown Source:102) at kotlinx.coroutines.x0.o0(Unknown Source:38) at kotlinx.coroutines.l.o(Unknown Source:107) at oa.b.c(Unknown Source:6) at oa.m.p(Unknown Source:89) at oa.j.j(Unknown Source:0) at k3.t2.i(Unknown Source:31) at k3.t2.f(Unknown Source:505) at k3.c2.m(Unknown Source:11) at x9.a.h(Unknown Source:8) at kotlinx.coroutines.m0.run(Unknown Source:102) at android.os.Handler.handleCallback(Handler.java:942) at android.os.Handler.dispatchMessage(Handler.java:99) at android.os.Looper.loopOnce(Looper.java:201) at android.os.Looper.loop(Looper.java:288) at android.app.ActivityThread.main(ActivityThread.java:7884) at java.lang.reflect.Method.invoke(Native Method) at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:936) Caused by: java.lang.NullPointerException at hb.d.A(Unknown Source:417) at n4.f.P0(Unknown Source:59) at f8.j.m(Unknown Source:171) at x9.a.h(Unknown Source:8) at kotlinx.coroutines.m0.run(Unknown Source:102) at kotlinx.coroutines.internal.f.run(Unknown Source:12) at kotlinx.coroutines.scheduling.l.run(Unknown Source:2) at kotlinx.coroutines.scheduling.a.run(Unknown Source:78) `
> 
> When accessing to the library that has mixed content fron the Home page, through "View all" in recently added to that library

Now the error does not appear, you can browse the library fine, but the library is not showing up in Libraries menu.

**Comment by jerojero** [comment]
The issue is still present, plus if you go into "View all" it just kind of becomes very buggy. Might have to re-do my libraries because of this :/
