### ISSUE TITLE
0.11.0 (18) Error loading data on Home screen

### ISSUE THREAD

**Issue by boekhold** [jarnedemeulemeester/findroid#360]
**Describe the bug**
Findroid 0.11.0 (18) shows "Error loading data" on home screen. However, My Media and Favorites work normally. Media also plays from those pages.

This did not happen on 0.10.1 (17). I have verified this on 2 devices (Samsung Galaxy Tab S6 and Honor Pad 8).

**To Reproduce**
1. Open Findroid
2. Go to Home page
3. See error

**Expected behavior**
Home page works, as it did in 0.10.1 (17)

**Stack Trace**
```
null
java.lang.NullPointerException
at hb.d.A(Unknown Source:417)
at n4.f.P0(Unknown Source:59)
at f8.n0.D(Unknown Source:120)
at f8.l.m(Unknown Source:12)
at x9.a.h(Unknown Source:8)
at kotlinx.coroutines.m0.run(Unknown Source:102)
at android.os.Handler.handleCallback(Handler.java:955)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loopOnce(Looper.java:206)
at android.os.Looper.loop(Looper.java:296)
at android.app.ActivityThread.main(ActivityThread.java:8971)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:569)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:976)
```

**Device info (please complete the following information):**
 - Device: Samsung Galaxy Tab S6
     - Android version: 12
     - App version: 0.11.0 (18)
     - Jellyfin version: 10.8.10
- Device: Honor Pad 8
     - Android version: 12
     - App version: 0.11.0 (18)
     - Jellyfin version: 10.8.10

**Comment by molitar** [comment]
Same exact error here with OnePlus 6T Android 10

**Comment by jarnedemeulemeester** [comment]
I'm investigating this.
Seems to be related to an episode which is not coupled to a season or series.
