### ISSUE TITLE
Not able to play an episode if any episode of the season is unfinished downloading/broken

### ISSUE THREAD

**Issue by TheFirstMonster** [jarnedemeulemeester/findroid#514]
**Describe the bug**
Findroid seems to cause Jellyfin to try to get metadata for every episode of the season which causes a code 500 to be returned if this fails for any episode. In my case this happened because ep 22 was less than 1% downloaded so I guess the mkv headers were not complete yet. I tested playing ep 1 which is fully downloaded successfully via Jellyfin Android Web Player, Internal Player and External Player as well as the FireTV Jellyfin app. 

**Expected behavior**
A broken file shouldn't effect any other episodes

Jellyfin log when playing the same file via official Jellyfin Android internal player:
`[15:15:47] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[15:15:47] [INF] [42] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Jellyfin Android, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E01.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=DirectPlay, TranscodeReason=0 ) media:/videos/d6fb320f-f762-beea-614c-9fc7163bc0ae/stream.mkv?MediaSourceId=d6fb320ff762beea614c9fc7163bc0ae&Static=true&VideoCodec=hevc&AudioCodec=dts&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Embed&Tag=8032e8766429201cddabce8c5a2440ff
[15:15:51] [INF] [58] Emby.Server.Implementations.Session.SessionManager: Playback stopped reported by app Jellyfin Android 2.5.3 playing An dich in 2000 Jahren - Der Fall von Shiganshina, Teil 1. Stopped at 3013 ms`

**Device info (please complete the following information):**
 - Android version: 13
 - App version: 0.13.0
 - Jellyfin version: 10.8.10

Jellyfin log when playing file via Findroid:
```
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E01.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/d6fb320f-f762-beea-614c-9fc7163bc0ae/stream?MediaSourceId=d6fb320ff762beea614c9fc7163bc0ae&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=8032e8766429201cddabce8c5a2440ff&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E02.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/5370a7a0-58a3-f121-1e64-d5abb09d8d44/stream?MediaSourceId=5370a7a058a3f1211e64d5abb09d8d44&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=935c4ef94858d4db3b33d1010fd98a69&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E03.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/f8e71700-e3ec-e62e-3509-d6fd1ed8cf97/stream?MediaSourceId=f8e71700e3ece62e3509d6fd1ed8cf97&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=96a60464cf63306a976743dc0379bd2d&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E04.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/8546d717-d54f-7da0-b0dd-3af56a963186/stream?MediaSourceId=8546d717d54f7da0b0dd3af56a963186&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=caa67fe8dd11214d69ba6d9e2425e4be&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [35] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [35] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E05.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/d01ef724-c352-7671-9426-a316cadcb10b/stream?MediaSourceId=d01ef724c35276719426a316cadcb10b&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=6a0b77c11ff981f67bf0014ebcb77ae7&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [22] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [22] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E06.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/fcd2d169-e8db-65da-801b-0d486350ba62/stream?MediaSourceId=fcd2d169e8db65da801b0d486350ba62&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=62229792da0f66ab0c2120719ca2f7b7&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [22] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [22] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E07.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/eff5092d-852e-5f42-0cc5-060e140c1ba4/stream?MediaSourceId=eff5092d852e5f420cc5060e140c1ba4&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=33acbd243ab69e2e8feb26e00dbe331f&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [31] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E08.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/79faecf4-7b12-ec2f-6f20-ba727b59e9a6/stream?MediaSourceId=79faecf47b12ec2f6f20ba727b59e9a6&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=cd92cf63f81e54923b6c3ee2795e3ab7&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E09.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/2c74f083-23a8-872b-378c-e7c32fb7b9c5/stream?MediaSourceId=2c74f08323a8872b378ce7c32fb7b9c5&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=83970361013e17de6a473e1f1f538ae4&TranscodeReasons=SubtitleCodecNotSupported
[14:50:55] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:55] [INF] [41] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E10.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/666efd2f-f255-d97c-5f87-0c6466f90401/stream?MediaSourceId=666efd2ff255d97c5f870c6466f90401&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=c79bdbccd1bacc5b2d36822536245318&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E11.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/555d2b9b-0e22-c6b5-06bc-eef5f596fd4f/stream?MediaSourceId=555d2b9b0e22c6b506bceef5f596fd4f&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=6eb81ca4a2f9626fad1a8fad036a601f&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E12.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/eb7b0247-2326-16ad-953b-9d93a9e340a4/stream?MediaSourceId=eb7b0247232616ad953b9d93a9e340a4&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=fb61e9eddd27a81cc806005501ddf36d&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E14.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/63fe6513-f0ff-9239-6515-75383c061716/stream?MediaSourceId=63fe6513f0ff9239651575383c061716&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=1c39ec132f731ffe437dfe0b8aca58b8&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E15.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/7362f38b-a54b-90c4-195d-bb98ccb0de3b/stream?MediaSourceId=7362f38ba54b90c4195dbb98ccb0de3b&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=f418ef4ec42d9270d8600dbe58f2bee2&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E16.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/ba84094d-fd5c-4b0f-dada-66694693b2f6/stream?MediaSourceId=ba84094dfd5c4b0fdada66694693b2f6&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=225be74eb2082aa397b0e4a628335088&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E19.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/db68535e-e675-4b3d-e3a3-a3e854a42517/stream?MediaSourceId=db68535ee6754b3de3a3a3e854a42517&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=cc05dcbc4c2fc6a6267f1e98f6f01948&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [3] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E20.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/a6429735-690b-9fa9-6dde-3ba18be19fd9/stream?MediaSourceId=a6429735690b9fa96dde3ba18be19fd9&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=74f6c1ba6b72a80e8ea9e97f7c33e061&TranscodeReasons=SubtitleCodecNotSupported
[14:50:56] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [INF] [8] Jellyfin.Api.Helpers.MediaInfoHelper: StreamBuilder.BuildVideoItem( Profile=Direct play all, Path=/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E21.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv, AudioStreamIndex=null, SubtitleStreamIndex=null ) => ( PlayMethod=Transcode, TranscodeReason=SubtitleCodecNotSupported ) media:/videos/0a43fdcb-9138-bf0b-6aa0-de6640cda0ea/stream?MediaSourceId=0a43fdcb9138bf0b6aa0de6640cda0ea&AudioStreamIndex=1&SubtitleStreamIndex=3&api_key=<token>&SubtitleMethod=Encode&RequireAvc=false&Tag=828fd0bffbe0b5ec52ed4a5c42c611bf&TranscodeReasons=SubtitleCodecNotSupported
[matroska,webm @ 0x55d8befa5f40] Format matroska,webm detected only with low score of 1, misdetection possible!
[matroska,webm @ 0x55d8befa5f40] 0x00 at pos 0 (0x0) invalid as first byte of an EBML number
[matroska,webm @ 0x55d8befa5f40] EBML header parsing failed
file:/data/Media/Downloads/Anime/Attack.on.Titan.S01.German.DL.DTS.1080p.BluRay.x265-ABJ/Attack.on.Titan.S01E22.German.DL.DTS.1080p.BluRay.x265-ABJ.mkv: Invalid data found when processing input
[14:50:56] [ERR] [35] MediaBrowser.Providers.TV.EpisodeMetadataService: Error in ffprobe
MediaBrowser.Common.FfmpegException: ffprobe failed - streams and format are both null.
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.MediaEncoding.Encoder.MediaEncoder.GetMediaInfoInternal(String inputPath, String primaryPath, MediaProtocol protocol, Boolean extractChapters, String probeSizeArgument, Boolean isAudio, Nullable`1 videoType, Boolean forceEnableLogging, CancellationToken cancellationToken)
   at MediaBrowser.Providers.MediaInfo.FFProbeVideoInfo.ProbeVideo[T](T item, MetadataRefreshOptions options, CancellationToken cancellationToken)
   at MediaBrowser.Providers.Manager.MetadataService`2.RunCustomProvider(ICustomMetadataProvider`1 provider, TItemType item, String logName, MetadataRefreshOptions options, RefreshResult refreshResult, CancellationToken cancellationToken)
[14:50:56] [INF] [22] Jellyfin.Api.Helpers.MediaInfoHelper: User policy for TempUser. EnablePlaybackRemuxing: True EnableVideoPlaybackTranscoding: True EnableAudioPlaybackTranscoding: True
[14:50:56] [ERR] [22] Jellyfin.Server.Middleware.ExceptionMiddleware: Error processing request. URL POST /Items/16190b3c-271d-bd72-bf86-9b2d5d4979bc/PlaybackInfo.
System.NullReferenceException: Object reference not set to an instance of an object.
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(MediaSourceInfo item, VideoOptions options)
   at MediaBrowser.Model.Dlna.StreamBuilder.BuildVideoItem(VideoOptions options)
   at Jellyfin.Api.Helpers.MediaInfoHelper.SetDeviceSpecificData(BaseItem item, MediaSourceInfo mediaSource, DeviceProfile profile, AuthorizationInfo auth, Nullable`1 maxBitrate, Int64 startTimeTicks, String mediaSourceId, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String playSessionId, Guid userId, Boolean enableDirectPlay, Boolean enableDirectStream, Boolean enableTranscoding, Boolean allowVideoStreamCopy, Boolean allowAudioStreamCopy, IPAddress ipAddress)
   at Jellyfin.Api.Controllers.MediaInfoController.GetPostedPlaybackInfo(Guid itemId, Nullable`1 userId, Nullable`1 maxStreamingBitrate, Nullable`1 startTimeTicks, Nullable`1 audioStreamIndex, Nullable`1 subtitleStreamIndex, Nullable`1 maxAudioChannels, String mediaSourceId, String liveStreamId, Nullable`1 autoOpenLiveStream, Nullable`1 enableDirectPlay, Nullable`1 enableDirectStream, Nullable`1 enableTranscoding, Nullable`1 allowVideoStreamCopy, Nullable`1 allowAudioStreamCopy, PlaybackInfoDto playbackInfoDto)
   at lambda_method1304(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Jellyfin.Server.Middleware.ServerStartupMessageMiddleware.Invoke(HttpContext httpContext, IServerApplicationHost serverApplicationHost, ILocalizationManager localizationManager)
   at Jellyfin.Server.Middleware.WebSocketHandlerMiddleware.Invoke(HttpContext httpContext, IWebSocketManager webSocketManager)
   at Jellyfin.Server.Middleware.IpBasedAccessValidationMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager)
   at Jellyfin.Server.Middleware.LanFilteringMiddleware.Invoke(HttpContext httpContext, INetworkManager networkManager, IServerConfigurationManager serverConfigurationManager)
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.QueryStringDecodingMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.ReDoc.ReDocMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
   at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Jellyfin.Server.Middleware.RobotsRedirectionMiddleware.Invoke(HttpContext httpContext)
   at Jellyfin.Server.Middleware.LegacyEmbyRouteRewriteMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.InvokeCore(HttpContext context)
   at Jellyfin.Server.Middleware.ResponseTimeMiddleware.Invoke(HttpContext context, IServerConfigurationManager serverConfigurationManager)
   at Jellyfin.Server.Middleware.ExceptionMiddleware.Invoke(HttpContext context)
```

Findroid Error:
```
Invalid HTTP status in response: 500
 rb.c: Invalid HTTP status in response: 500
	at qb.f.h(Unknown Source:465)
	at qb.e.s(Unknown Source:17)
	at r9.a.i(Unknown Source:8)
	at ia.j0.run(Unknown Source:107)
	at androidx.appcompat.widget.j.run(Unknown Source:878)
	at oa.l.run(Unknown Source:2)
	at oa.a.run(Unknown Source:95)
```

**Comment by Jcuhfehl** [comment]
Looking at the jellyfin logs, it looks like it's trying to transcode the media, which findroid doesn't support. Does playback work on the same media when it isn't downloaded?
