### ISSUE TITLE
Home (tab) error, not loading. Bug? 

### ISSUE THREAD

**Issue by snvoid** [jarnedemeulemeester/findroid#586]
**Describe the bug**
An error is displayed at home (tab)

**To Reproduce**

1) Just open app, wait for home tab to load 
2) See error instead 

**Expected behavior**
Displaying the home page, way it works on jellyfin web. Things like media you haven't finished watching, etc.

**Screenshots**

**Device info (please complete the following information):**
 - Android version: 10
 - App version: 0.13.1 (22)

**Additional context**

I searched for similar issues and found this one but doesn't seem like that user uploaded the full error message. I didn't understand what the response meant. I tried this on two servers that were shared with me. Neither is my own jellyfin server but i'm getting this error on both.

https://github.com/jarnedemeulemeester/findroid/issues/223 

Getting this in the error message: 

Socket timed out
 rb.e: Socket timed out
	at qb.f.h(Unknown Source:608)
	at qb.e.s(Unknown Source:17)
	at r9.a.i(Unknown Source:8)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at ia.j0.run(Unknown Source:107)
	at androidx.appcompat.widget.j.run(Unknown Source:878)
	at pa.l.run(Unknown Source:2)
	at pa.a.run(Unknown Source:95)
Caused by: x8.b: Socket timeout has expired [url=https://jellyfin.ozone.blank/Shows/NextUp?userId=0c3434b-1bc3-4f46-8a86-7cae8d61413c&limit=9&enableTotalRecordCount=true&disableFirstEpisode=false&enableRewatching=false, socket_timeout=10000] ms
	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(Unknown Source:59)
	at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(Unknown Source:22)
	at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(Unknown Source:0)
	at j8.a.a(Unknown Source:26)
	at eb.g.run(Unknown Source:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.SocketTimeoutException: timeout
	at hb.z.k(Unknown Source:4)
	at hb.z.m(Unknown Source:8)
	at hb.u.e(Unknown Source:28)
	at eb.e.e(Unknown Source:2)
	at fb.b.a(Unknown Source:267)
	at fb.f.b(Unknown Source:132)
	at eb.a.a(Unknown Source:99)
	at fb.f.b(Unknown Source:132)
	at cb.a.a(Unknown Source:121)
	at fb.f.b(Unknown Source:132)
	at fb.a.a(Unknown Source:144)
	at fb.f.b(Unknown Source:132)
	at fb.g.a(Unknown Source:151)
	at fb.f.b(Unknown Source:132)
	at eb.j.g(Unknown Source:95)
	at eb.g.run(Unknown Source:35)
	... 3 more

**Comment by snvoid** [comment]
> > Socket timed out
> 
> It sounds like the loading took too long. Are you on slow internet or is your server slow? You can increase the timeout time in settings>network and see if that fixes your issue

Its not my own server, but friends of mine. One of the servers isn't that great, but one of them is high end with fast internet. My internet is fast as well so it don't think its that. 

I tried increasing all the values under network in Findroid but i seem to be getting very similar error regardless of what the values are changed to. Weirdly enough, even the socket time out seems to show up as socket_timeout=10000] ms in the new error report even though i changed it to 600000. Could still be something on my end or the server end but wanted to just give a report in case there is something that can be fixed within the app 

Thanks

---

Socket timed out
 rb.e: Socket timed out
	at qb.f.h(Unknown Source:608)
	at qb.e.s(Unknown Source:17)
	at r9.a.i(Unknown Source:8)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at d9.m.d(Unknown Source:99)
	at d9.l.i(Unknown Source:17)
	at r9.a.i(Unknown Source:31)
	at ia.j0.run(Unknown Source:107)
	at androidx.appcompat.widget.j.run(Unknown Source:878)
	at pa.l.run(Unknown Source:2)
	at pa.a.run(Unknown Source:95)
Caused by: x8.b: Socket timeout has expired [url=https://redacted/Shows/NextUp?userId=0c04c60b-sdf3-4f36-8b86-7cae8d61614c&limit=9&enableTotalRecordCount=true&disableFirstEpisode=false&enableRewatching=false, socket_timeout=10000] ms
	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(Unknown Source:59)
	at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(Unknown Source:22)
	at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(Unknown Source:0)
	at j8.a.a(Unknown Source:26)
	at eb.g.run(Unknown Source:116)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:919)
Caused by: java.net.SocketTimeoutException: timeout
	at hb.z.k(Unknown Source:4)
	at hb.z.m(Unknown Source:8)
	at hb.u.e(Unknown Source:28)
	at eb.e.e(Unknown Source:2)
	at fb.b.a(Unknown Source:267)
	at fb.f.b(Unknown Source:132)
	at eb.a.a(Unknown Source:99)
	at fb.f.b(Unknown Source:132)
	at cb.a.a(Unknown Source:121)
	at fb.f.b(Unknown Source:132)
	at fb.a.a(Unknown Source:144)
	at fb.f.b(Unknown Source:132)
	at fb.g.a(Unknown Source:151)
	at fb.f.b(Unknown Source:132)
	at eb.j.g(Unknown Source:95)
	at eb.g.run(Unknown Source:35)
	... 3 more

**Comment by Sgtmajor0205** [comment]
Have the same issue everything else works fine just the home screen

**Comment by Sgtmajor0205** [comment]
> Seems like a slow server issue. Changing the network settings in Findroid requires a full app restart for those values to apply and should fix your issue.

I have changed the values have restarted the app and I still get the same issue.

Works fine on the jellyfin app but like the findroid appearance on phone
