### ISSUE TITLE
"Unknown SSL error" - TLS is fine everywhere else

### ISSUE THREAD

**Issue by FunctionDJ** [jarnedemeulemeester/findroid#689]
**Describe the bug**
When opening the latest findroid 2024.02, it's unable to load any data (TV/movie overview) from the server. Showing details says "Unknown SSL error" (see below)

**To Reproduce**
not sure how to make it reproduceable, but i get the error right away when opening the app.

**Expected behavior**
being able to see the default 'home screen' of shows and movies.

**Screenshots**
![Screenshot_2024-03-12-23-59-18-16_aff99014c254344a005aaf8c1683039d.jpg](https://github.com/jarnedemeulemeester/findroid/assets/34871211/a720cb98-d73c-49a1-bd21-f1bab074f767)

**Device info (please complete the following information):**
 - Device: OnePlus 7 Pro
 - Android version: 12
 - App version: 2024.02
 - Jellyfin version: 10.8.13

**Additional context**
Regular Jellyfin app loads fine and Jellyfin interface also loads fine in other browsers and on my LG TV (web wrapper). When checking the TLS certificate everything looks fine too.
I use Caddy with Cloudflare DNS and a domain i bought to get certificates. I use a local DNS to use a local network IP when i'm at home to not route Jellyfin traffic through the internet, but this issue exists regardless of which IP i use to get to Jellyfin, private or public.

Details text:

```
Unknown SSL error occurred
 bc.d: Unknown SSL error occurred
	at ac.h.g(Unknown Source:565)
	at ac.g.q(Unknown Source:17)
	at ca.a.m(Unknown Source:8)
	at p9.m.d(Unknown Source:103)
	at p9.l.m(Unknown Source:17)
	at ca.a.m(Unknown Source:31)
	at p9.m.d(Unknown Source:103)
	at p9.l.m(Unknown Source:17)
	at ca.a.m(Unknown Source:31)
	at p9.m.d(Unknown Source:103)
	at p9.l.m(Unknown Source:17)
	at ca.a.m(Unknown Source:31)
	at p9.m.d(Unknown Source:103)
	at p9.l.m(Unknown Source:17)
	at ca.a.m(Unknown Source:31)
	at ta.m0.run(Unknown Source:104)
	at l.j.run(Unknown Source:12)
	at za.l.run(Unknown Source:2)
	at za.a.run(Unknown Source:93)
Caused by: javax.net.ssl.SSLHandshakeException: Chain validation failed
	at com.android.org.conscrypt.SSLUtils.toSSLHandshakeException(SSLUtils.java:356)
	at com.android.org.conscrypt.ConscryptEngine.convertException(ConscryptEngine.java:1134)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1089)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:876)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:747)
	at com.android.org.conscrypt.ConscryptEngine.unwrap(ConscryptEngine.java:712)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.processDataFromSocket(ConscryptEngineSocket.java:896)
	at com.android.org.conscrypt.ConscryptEngineSocket$SSLInputStream.-$$Nest$mprocessDataFromSocket(Unknown Source:0)
	at com.android.org.conscrypt.ConscryptEngineSocket.doHandshake(ConscryptEngineSocket.java:236)
	at com.android.org.conscrypt.ConscryptEngineSocket.startHandshake(ConscryptEngineSocket.java:218)
	at ob.m.g(Unknown Source:105)
	at ob.m.c(Unknown Source:173)
	at ob.f.a(Unknown Source:719)
	at ob.a.a(Unknown Source:57)
	at pb.f.b(Unknown Source:121)
	at mb.a.a(Unknown Source:129)
	at pb.f.b(Unknown Source:121)
	at pb.a.a(Unknown Source:142)
	at pb.f.b(Unknown Source:121)
	at pb.g.a(Unknown Source:146)
	at pb.f.b(Unknown Source:121)
	at ob.j.g(Unknown Source:96)
	at ob.g.run(Unknown Source:47)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
Caused by: java.security.cert.CertificateException: Chain validation failed
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:719)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:549)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:570)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrustedRecursive(TrustManagerImpl.java:615)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:505)
	at com.android.org.conscrypt.TrustManagerImpl.checkTrusted(TrustManagerImpl.java:425)
	at com.android.org.conscrypt.TrustManagerImpl.getTrustedChainForServer(TrustManagerImpl.java:353)
	at android.security.net.config.NetworkSecurityTrustManager.checkServerTrusted(NetworkSecurityTrustManager.java:94)
	at android.security.net.config.RootTrustManager.checkServerTrusted(RootTrustManager.java:90)
	at com.android.org.conscrypt.ConscryptEngineSocket$2.checkServerTrusted(ConscryptEngineSocket.java:163)
	at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:260)
	at com.android.org.conscrypt.ConscryptEngine.verifyCertificateChain(ConscryptEngine.java:1638)
	at com.android.org.conscrypt.NativeCrypto.ENGINE_SSL_read_direct(Native Method)
	at com.android.org.conscrypt.NativeSsl.readDirectByteBuffer(NativeSsl.java:568)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextDataDirect(ConscryptEngine.java:1095)
	at com.android.org.conscrypt.ConscryptEngine.readPlaintextData(ConscryptEngine.java:1079)
	... 23 more
Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:135)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:222)
	at sun.security.provider.certpath.PKIXCertPathValidator.validate(PKIXCertPathValidator.java:140)
	at sun.security.provider.certpath.PKIXCertPathValidator.engineValidate(PKIXCertPathValidator.java:79)
	at java.security.cert.CertPathValidator.validate(CertPathValidator.java:309)
	at com.android.org.conscrypt.TrustManagerImpl.verifyChain(TrustManagerImpl.java:715)
	... 39 more
Caused by: java.security.cert.CertPathValidatorException: Response is unreliable: its validity interval is out-of-date
	at sun.security.provider.certpath.OCSPResponse.verify(OCSPResponse.java:619)
	at sun.security.provider.certpath.RevocationChecker.checkOCSP(RevocationChecker.java:709)
	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:363)
	at sun.security.provider.certpath.RevocationChecker.check(RevocationChecker.java:337)
	at sun.security.provider.certpath.PKIXMasterCertPathValidator.validate(PKIXMasterCertPathValidator.java:125)
	... 44 more

```

**Comment by FunctionDJ** [comment]
My TLS cert expired today. After renewing, the app works again.

The behaviour i observed is still weird. Maybe related to some timezone differences causing the cert to be rejected earlier than it should?

**Comment by Natanel-Shitrit** [comment]
It doesn't sound like an issue to me..
I think Findroid shouldn't do anything "extra" if the certificate is expired.
It's clearly saying an SSL issue in the error.

**Comment by FunctionDJ** [comment]
I never ran into this issue again and it was most likely because of my cert and some caching oddities and not a bug in Findroid. Closing the issue.
