### ISSUE TITLE
Open the home page and report an error "Socket timed out"

### ISSUE THREAD

**Issue by skywolf123** [jarnedemeulemeester/findroid#692]
**Describe the bug**
Open the home page and report an error "Socket timed out"

**To Reproduce**
1. Select a server.
2. View the home page
3. See error

**Device info (please complete the following information):**
 - Device: Redmi K20 Pro
 - Android version: 11
 - App version: v0.14.1 (24)
 - Jellyfin version: 10.8.13

**Additional context**
Socket timed out
 G5.e: Socket timed out
	at F5.g.d(Unknown Source:613)
	at F5.f.q(Unknown Source:17)
	at C4.a.l(Unknown Source:8)
	at p4.m.d(Unknown Source:103)
	at p4.l.l(Unknown Source:17)
	at C4.a.l(Unknown Source:31)
	at p4.m.d(Unknown Source:103)
	at p4.l.l(Unknown Source:17)
	at C4.a.l(Unknown Source:31)
	at p4.m.d(Unknown Source:103)
	at p4.l.l(Unknown Source:17)
	at C4.a.l(Unknown Source:31)
	at p4.m.d(Unknown Source:103)
	at p4.l.l(Unknown Source:17)
	at C4.a.l(Unknown Source:31)
	at Y4.N.run(Unknown Source:104)
	at m.j.run(Unknown Source:12)
	at e5.m.run(Unknown Source:2)
	at e5.a.run(Unknown Source:97)
Caused by: j4.b: Socket timeout has expired [url=http://192.168.31.10:8096/Users/5fecbf5d-7d79-4c9e-917a-37737c0712ad/Items/Resume?limit=12&includeItemTypes=Movie&includeItemTypes=Episode&enableTotalRecordCount=true&enableImages=true&excludeActiveSessions=false, socket_timeout=10000] ms
	at io.ktor.client.features.HttpTimeoutKt.SocketTimeoutException(Unknown Source:59)
	at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(Unknown Source:23)
	at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(Unknown Source:0)
	at V3.a.b(Unknown Source:35)
	at t5.g.run(Unknown Source:143)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
	at java.lang.Thread.run(Thread.java:923)
Caused by: java.net.SocketTimeoutException: timeout
	at C5.I.k(Unknown Source:4)
	at C5.e.E(Unknown Source:155)
	at C5.D.O(Unknown Source:49)
	at C5.D.T(Unknown Source:33)
	at v5.h.f(Unknown Source:44)
	at t5.e.e(Unknown Source:2)
	at u5.b.a(Unknown Source:266)
	at u5.f.b(Unknown Source:121)
	at t5.a.a(Unknown Source:96)
	at u5.f.b(Unknown Source:121)
	at r5.a.a(Unknown Source:129)
	at u5.f.b(Unknown Source:121)
	at u5.a.a(Unknown Source:142)
	at u5.f.b(Unknown Source:121)
	at u5.g.a(Unknown Source:146)
	at u5.f.b(Unknown Source:121)
	at t5.j.g(Unknown Source:96)
	at t5.g.run(Unknown Source:47)
	... 3 more
Caused by: java.net.SocketTimeoutException: Read timed out
	at java.net.SocketInputStream.socketRead0(Native Method)
	at java.net.SocketInputStream.socketRead(SocketInputStream.java:119)
	at java.net.SocketInputStream.read(SocketInputStream.java:176)
	at java.net.SocketInputStream.read(SocketInputStream.java:144)
	at C5.e.E(Unknown Source:49)
	at C5.e.E(Unknown Source:128)
	... 19 more

**Comment by Natanel-Shitrit** [comment]
Hey 😄
Looks like the connection to the server has timed out, this can occur when:
- Your internet connection is slow / not working.
- Your server is slow to respond / now working.

Please make sure you have a good internet connection and the server is up and running.
You can try to increase the socket timeout in the settings (settings→network) to check if the server response is slow.

Hope this helps!

**Comment by Natanel-Shitrit** [comment]
10000ms = 10 seconds.
If your response takes "*about 14-15 seconds*", you should increase it - try to set it to 20000ms and check again.

**Comment by skywolf123** [comment]
I changed it to 100000, but I still got the same error report.
100000ms = 100 seconds

**Comment by Natanel-Shitrit** [comment]
> I changed it to 100000, but I still got the same error report.
> 100000ms = 100 seconds

Have you restarted the app?
It takes effect only after restart.

**Comment by skywolf123** [comment]
yes, I restarted the app.
now, I changed it to 60000, It's working properly. 
Maybe this parameter is less than 65535, I guess. 
But anyway, it's ok. I shut down the issue.
