### ISSUE TITLE
连接超时，是什么情况

### ISSUE THREAD

**Issue by yanwuhuo1** [jarnedemeulemeester/findroid#700]
Connection timed out
G5.e: Connection timed out
at F5.g.d(Unknown Source:628)
at F5.f.q(Unknown Source:17)
at C4.a.l(Unknown Source:8)
at p4.m.d(Unknown Source:103)
at p4.l.l(Unknown Source:17)
at C4.a.l(Unknown Source:31)
at p4.m.d(Unknown Source:103)
at p4.l.l(Unknown Source:17)
at C4.a.l(Unknown Source:31)
at p4.m.d(Unknown Source:103)
at p4.l.l(Unknown Source:17)
at C4.a.l(Unknown Source:31)
at p4.m.d(Unknown Source:103)
at p4.l.l(Unknown Source:17)
at C4.a.l(Unknown Source:31)
at Y4.N.run(Unknown Source:104)
at m.j.run(Unknown Source:12)
at e5.m.run(Unknown Source:2)
at e5.a.run(Unknown Source:97)
Caused by: j4.a: Connect timeout has expired [url=http://192.168.31.203:8096/Users/577bd715-a5db-4b74-afe2-1fcdcc154b4e/Items/Resume?limit=12&includeItemTypes=Movie&includeItemTypes=Episode&enableTotalRecordCount=true&enableImages=true&excludeActiveSessions=false, connect_timeout=6000 ms]
at io.ktor.client.features.HttpTimeoutKt.ConnectTimeoutException(SourceFile:8)
at io.ktor.client.engine.okhttp.OkUtilsKt.mapOkHttpException(Unknown Source:17)
at io.ktor.client.engine.okhttp.OkUtilsKt.access$mapOkHttpException(Unknown Source:0)
at V3.a.b(Unknown Source:35)
at t5.g.run(Unknown Source:143)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
at java.lang.Thread.run(Thread.java:1012)
Caused by: java.net.SocketTimeoutException: failed to connect to /192.168.31.202 (port 8096) from /10.211.44.3 (port 39276) after 6000ms
at libcore.io.IoBridge.connectErrno(IoBridge.java:235)
at libcore.io.IoBridge.connect(IoBridge.java:179)
at java.net.PlainSocketImpl.socketConnect(PlainSocketImpl.java:142)
at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:390)
at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:230)
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:212)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:436)
at java.net.Socket.connect(Socket.java:646)
at x5.l.e(Unknown Source:5)
at t5.m.e(Unknown Source:73)
at t5.m.c(Unknown Source:169)
at t5.f.a(Unknown Source:719)
at t5.a.a(Unknown Source:57)
at u5.f.b(Unknown Source:121)
at r5.a.a(Unknown Source:129)
at u5.f.b(Unknown Source:121)
at u5.a.a(Unknown Source:142)
at u5.f.b(Unknown Source:121)
at u5.g.a(Unknown Source:146)
at u5.f.b(Unknown Source:121)
at t5.j.g(Unknown Source:96)
at t5.g.run(Unknown Source:47)
... 3 more

**Comment by yanwuhuo1** [comment]
Don't support China?

**Comment by Natanel-Shitrit** [comment]
Hey 😄
Looks like the connection to the server has timed out, this can occur when:
- Your internet connection is slow / not working.
- Your server is slow to respond / not working.

Please make sure you have a good internet connection and the server is up and running.
You can try to increase the socket timeout in the settings (settings→network) to fix the problem if the server is slow to respond.

Hope this helps!
