### ISSUE TITLE
Cannot log in when device name is blank

### ISSUE THREAD

**Issue by niravjdn** [jarnedemeulemeester/findroid#846]
**Describe the bug**
I am getting an error while trying to login to jellyfin server 10.9.0 from Findroid on Android 13 Lenovo tablet. It works on my Android 11 Samsung Note 10 but only getting error on Tablet.

**To Reproduce**
1. Enter Server url as 192.168.2.xxx:8096
2. Enter username and password
3. Error will be shown

**Screenshots**
https://imgur.com/df0STEg

**Device info (please complete the following information):**
 - Device: [e.g. Lenovo Tab P11 2nd Gen]
 - Android version: [e.g. 13]
 - App version: [e.g. v0.15.2 )]
 - Jellyfin version: [e.g. 10.9.0]

Logs on Jellyfin Server:

```
AuthenticateByName.
System.ArgumentException: The value cannot be an empty string. (Parameter 'request.DeviceName')
   at System.ArgumentException.ThrowNullOrEmptyException(String argument, String paramName)
   at System.ArgumentException.ThrowIfNullOrEmpty(String argument, String paramName)
   at Emby.Server.Implementations.Session.SessionManager.AuthenticateNewSessionInternal(AuthenticationRequest request, Boolean enforcePassword)
   at Jellyfin.Api.Controllers.UserController.AuthenticateUserByName(AuthenticateUserByName request)
   at lambda_method1733(Closure, Object)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at
```

**Comment by jarnedemeulemeester** [comment]
It seems like your device name is an empty string.
Please check the name of your device in the settings app and set it to a non empty string.

**Comment by niravjdn** [comment]
Device![image](https://github.com/user-attachments/assets/7833b007-1c0b-4217-bbe1-0175fb166055) name is already set.

**Comment by niravjdn** [comment]
@jarnedemeulemeester Please help

**Comment by jarnedemeulemeester** [comment]
This is an issue that Lenovo needs to solve. We are using the correct the correct Android API to retrieve the device name.
What happens if you change the device name? Do you still get the error?

**Comment by niravjdn** [comment]
Can you please tell me where do we try to get device name in code? For my use case, I can compile app locally by hardcoding it or trying to get Bluetooth adapter name.

**Comment by niravjdn** [comment]
If I use devuce info app from playstore, It is able to fetch devuce name.

![image](https://github.com/user-attachments/assets/03c9507e-8aae-465d-9c59-003392f4f6e7)

**Comment by jarnedemeulemeester** [comment]
The device name is read in the Jellyfin Kotlin SDK
https://github.com/jellyfin/jellyfin-sdk-kotlin/blob/master/jellyfin-core/src/androidMain/kotlin/org/jellyfin/sdk/android/AndroidDevice.kt#L12

I will try pushing a workaround to the SDK upstream.

**Comment by niravjdn** [comment]
Thanks. Waiting for fix to be shipped to app 😊

**Comment by jarnedemeulemeester** [comment]
The fix has been merged upstream!
It is expected to ship around the time that Jellyfin 10.10.1 releases

**Comment by jarnedemeulemeester** [comment]
This should now be fixed when a new release of Findroid is published
